title: Dum Dev Blog
url: https://projects.abhinavsarkar.net/dum-blog
description: The blog for the Dum programming language.
authors:
  - name: Abhinav Sarkar
    uri: https://abhinavsarkar.net/about/
    email: abhinav@abhinavsarkar.net
    copyright_year: "2026"
