title: Shake Blog
url: https://abhin4v.github.io/shake-blog/
description: An example blog build on Shake.
authors:
  - name: Abhinav Sarkar
    uri: https://abhinavsarkar.net/about/
    email: abhinav@abhinavsarkar.net
    copyright_year: "2026"
